import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import { ThemeProvider } from "@/context/ContextApi";
import { ApiProvider } from "@/context/Apidata";
import { CartProvider } from "@/context/CartContext";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white dark:bg-gray-900 `}
      >
        <ThemeProvider>
          <ApiProvider>
            <CartProvider>
              <Navbar />
              {children}
              <Footer/>
            </CartProvider>
          </ApiProvider>
        </ThemeProvider>
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
